# Generated by Django 4.0.4 on 2022-05-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='title',
            field=models.CharField(default='Res', max_length=255),
            preserve_default=False,
        ),
    ]
